# Generated by Django 4.1 on 2024-11-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
