# Generated by Django 4.1 on 2024-11-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_emp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
